Repository Neo-Diamons/Arcade, pull requests merged in 2024-04, with the labels that each got.

#15 docs(README): add README.md.
  README.md
  docs/Doxyfile
Labels: documentation

#16 Snake
  assets/lose.png
  lib/ncurses/Ncurses.cpp
  lib/sdl2/SDL.cpp
  lib/sfml/Sfml.cpp
  lib/snake/Snake.cpp
Labels: bug, enhancement, invalid

#17 Dev
  Makefile
  README.md
  assets/lose.png
  assets/test.TTF
  docs/Doxyfile
  include/DrawObject/DrawRect.hpp
  lib/ncurses/Ncurses.cpp
  lib/sdl2/SDL.cpp
  lib/sdl2/SDL.hpp
  lib/sdl2/SDLKeys.cpp
  lib/sdl2/SDLKeys.hpp
  lib/sfml/Sfml.cpp
  lib/sfml/Sfml.hpp
  lib/sfml/SfmlKey.cpp
  lib/sfml/SfmlKey.hpp
  lib/snake/Snake.cpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: bug, documentation, enhancement, invalid

#18 DLLoader
  include/IGame.hpp
  include/IGraphical.hpp
  include/LibraryType.h
  lib/ncurses/Ncurses.cpp
  lib/sdl2/SDL.cpp
  lib/sfml/Sfml.cpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: enhancement

#19 DLLoader
  include/IGame.hpp
  include/IGraphical.hpp
  include/LibraryType.h
  lib/ncurses/Ncurses.cpp
  lib/sdl2/SDL.cpp
  lib/sfml/Sfml.cpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: enhancement

#20 Set graphical library to 60fps.
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/sdl2/SDL.cpp
  lib/sdl2/SDL.hpp
  lib/sdl2/SDLKeys.hpp
  lib/sfml/Sfml.cpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
Labels: enhancement

#22 fix(fps): invalid factor for ncurses fps.
  lib/ncurses/Ncurses.cpp
Labels: bug

#21 Dev
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/sdl2/SDL.cpp
  lib/sdl2/SDL.hpp
  lib/sdl2/SDLKeys.hpp
  lib/sfml/Sfml.cpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
Labels: enhancement

#23 Snake
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
Labels: enhancement

#24 fix(core): crash issue.
  src/Core.cpp
Labels: bug

#26 Dev
  Makefile
  assets/win.png
  include/LibraryType.hpp
  lib/ncurses/Ncurses.cpp
  lib/nibbler/Nibbler.cpp
  lib/nibbler/Nibbler.hpp
  lib/sdl2/SDL.cpp
  lib/sfml/Sfml.cpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: enhancement
