Repository Neo-Diamons/Arcade, pull requests merged in 2024-03, with the labels that each got.

#1 Key
  .github/workflows/doxygen.yml
  .github/workflows/mirror.yml
  .github/workflows/tests.yml
  .gitignore
  Makefile
  docs/Doxyfile
  docs/style/doxygen-awesome.css
  include/Color.hpp
  include/Game.hpp
  include/Graphical.hpp
  include/Key.hpp
  include/Texture.hpp
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/ncurses/NcursesKey.cpp
  lib/ncurses/NcursesKey.hpp
  src/Core.cpp
  src/Core.hpp
  src/Main.cpp
Labels: enhancement

#2 Fix github action which create github page depending of the doc.
  .github/workflows/doxygen.yml
  .github/workflows/tests.yml
Labels: documentation

#3 Core
  .github/workflows/tests.yml
  .gitignore
  Makefile
  include/IGame.hpp
  include/IGraphical.hpp
  include/IKey.hpp
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/ncurses/NcursesKey.cpp
  lib/ncurses/NcursesKey.hpp
  src/Core.cpp
  src/Core.hpp
Labels: bug, enhancement

#5 Core
  .github/workflows/tests.yml
  .gitignore
  Makefile
  include/IGame.hpp
  include/IGraphical.hpp
  include/IKey.hpp
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/ncurses/NcursesKey.cpp
  lib/ncurses/NcursesKey.hpp
  src/Core.cpp
  src/Core.hpp
Labels: enhancement

#6 Ncurses
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
  src/Main.cpp
Labels: enhancement

#7 Snake
  Makefile
  include/Color.hpp
  include/IGame.hpp
  include/IGraphical.hpp
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/ncurses/NcursesKey.hpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: enhancement

#8 Dev
  Makefile
  include/Color.hpp
  include/IGame.hpp
  include/IGraphical.hpp
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/ncurses/NcursesKey.hpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: enhancement

#9 feat(graphical): add new abstract layer to the graphical.
  Makefile
  include/DrawObject/DrawFillRect.hpp
  include/DrawObject/DrawObject.hpp
  include/DrawObject/DrawRect.hpp
  include/DrawObject/DrawText.hpp
  include/DrawObject/DrawTexture.hpp
  include/IGame.hpp
  include/IGraphical.hpp
  lib/ncurses/Ncurses.cpp
  lib/ncurses/Ncurses.hpp
  lib/snake/Snake.cpp
  lib/snake/Snake.hpp
  src/Core.cpp
  src/Core.hpp
Labels: enhancement

#11 fix(fix/loading): not setting the good index at init and fix reload f…
  lib/sdl2/SDL.cpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: bug

#12 merge(dev): Merge lib-sdl branch into dev branch
  Makefile
  assets/Freedom.ttf
  assets/lose.png
  assets/test.TTF
  lib/sdl2/SDL.cpp
  lib/sdl2/SDL.hpp
  lib/sdl2/SDLKeys.cpp
  lib/sdl2/SDLKeys.hpp
  src/Core.cpp
  src/Core.hpp
  src/DLLoader.hpp
Labels: enhancement
